package dev.def750.moddsniczego.disc

data class MusicDiscDefinition(
    val id: String,
    val title: String,
    val soundPath: String,
    val lengthInSeconds: Float,
    val comparatorOutput: Int,
)

object ModDiscDefinitions {
    val ALL = listOf(
        MusicDiscDefinition(
            id = "signal",
            title = "Ludicin - Signal",
            soundPath = "discs/signal",
            lengthInSeconds = 136.6f,
            comparatorOutput = 1,
        ),
        MusicDiscDefinition(
            id = "acid_god",
            title = "Yuta Imai - Acid God",
            soundPath = "discs/acid_god",
            lengthInSeconds = 145.8f,
            comparatorOutput = 2,
        ),
        MusicDiscDefinition(
            id = "lolit_speed",
            title = "DJ Sharpnel - Lolit Speed",
            soundPath = "discs/lolit_speed",
            lengthInSeconds = 408.5f,
            comparatorOutput = 3,
        ),
        MusicDiscDefinition(
            id = "555",
            title = "RoughSketch - 555 (Please call me \"Go! Go! Go!\")",
            soundPath = "discs/555",
            lengthInSeconds = 122.9f,
            comparatorOutput = 4,
        ),
        MusicDiscDefinition(
            id = "materialize_anything",
            title = "anubasu-anubasu - Materialize Anything",
            soundPath = "discs/materialize_anything",
            lengthInSeconds = 139.3f,
            comparatorOutput = 5,
        ),
        MusicDiscDefinition(
            id = "axion",
            title = "Sakuzyo - AXION",
            soundPath = "discs/axion",
            lengthInSeconds = 156.4f,
            comparatorOutput = 6,
        ),
        MusicDiscDefinition(
            id = "birdy_wings",
            title = "Birdy - Wings (Nu:Logic Remix)",
            soundPath = "discs/birdy_wings",
            lengthInSeconds = 381.4f,
            comparatorOutput = 7,
        ),
        MusicDiscDefinition(
            id = "kannagi",
            title = "BlackY feat. Risa Yuzuki - Kannagi",
            soundPath = "discs/kannagi",
            lengthInSeconds = 134.1f,
            comparatorOutput = 8,
        ),
        MusicDiscDefinition(
            id = "black_or_white",
            title = "BlackYooh vs. siromaru - BLACK or WHITE? (Extended)",
            soundPath = "discs/black_or_white",
            lengthInSeconds = 350.0f,
            comparatorOutput = 9,
        ),
        MusicDiscDefinition(
            id = "planet_shaper",
            title = "Camellia - PLANET//SHAPER",
            soundPath = "discs/planet_shaper",
            lengthInSeconds = 418.0f,
            comparatorOutput = 10,
        ),
        MusicDiscDefinition(
            id = "blastix_riotz",
            title = "Camellia as \"Bang Riot\" - Blastix Riotz",
            soundPath = "discs/blastix_riotz",
            lengthInSeconds = 127.8f,
            comparatorOutput = 11,
        ),
        MusicDiscDefinition(
            id = "gregtech",
            title = "Cheapex - live @ Need 4 Beat",
            soundPath = "discs/gregtech",
            lengthInSeconds = 104.6f,
            comparatorOutput = 12,
        ),
        MusicDiscDefinition(
            id = "cocodrilo",
            title = "Pollo - Cocodrilo",
            soundPath = "discs/cocodrilo",
            lengthInSeconds = 210.8f,
            comparatorOutput = 13,
        ),
        MusicDiscDefinition(
            id = "ea_nasir",
            title = "Complaint to Ea-Nasir",
            soundPath = "discs/ea_nasir",
            lengthInSeconds = 154.3f,
            comparatorOutput = 14,
        ),
        MusicDiscDefinition(
            id = "ball_hard",
            title = "crafter2011 - ball hard",
            soundPath = "discs/ball_hard",
            lengthInSeconds = 93.7f,
            comparatorOutput = 15,
        ),
        MusicDiscDefinition(
            id = "end_time",
            title = "Cres. - End Time",
            soundPath = "discs/end_time",
            lengthInSeconds = 137.5f,
            comparatorOutput = 1,
        ),
        MusicDiscDefinition(
            id = "titanomachia",
            title = "D-D-Dice vs. siromaru - Titanomachia",
            soundPath = "discs/titanomachia",
            lengthInSeconds = 127.7f,
            comparatorOutput = 2,
        ),
        MusicDiscDefinition(
            id = "dimension_wars",
            title = "Kyutatsuki - Dimension Wars",
            soundPath = "discs/dimension_wars",
            lengthInSeconds = 406.3f,
            comparatorOutput = 3,
        ),
        MusicDiscDefinition(
            id = "joe_thunder",
            title = "DJ Myosuke - Joe Thunder",
            soundPath = "discs/joe_thunder",
            lengthInSeconds = 164.9f,
            comparatorOutput = 4,
        ),
        MusicDiscDefinition(
            id = "chickencore",
            title = "DJ Myosuke - Bikkuri Extreme Chickencore",
            soundPath = "discs/chickencore",
            lengthInSeconds = 195.0f,
            comparatorOutput = 5,
        ),
        MusicDiscDefinition(
            id = "snows",
            title = "Jea - Snows ~Soshite Kise Ki~",
            soundPath = "discs/snows",
            lengthInSeconds = 325.9f,
            comparatorOutput = 6,
        ),
        MusicDiscDefinition(
            id = "joe_fight",
            title = "DJ Myosuke - Joe Fight (Joe Fight Remix)",
            soundPath = "discs/joe_fight",
            lengthInSeconds = 187.8f,
            comparatorOutput = 7,
        ),
        MusicDiscDefinition(
            id = "daisycutter",
            title = "ETIA. - Daisycutter",
            soundPath = "discs/daisycutter",
            lengthInSeconds = 124.5f,
            comparatorOutput = 8,
        ),
        MusicDiscDefinition(
            id = "fallen_symphony",
            title = "Ludicin - Fallen Symphony (?)",
            soundPath = "discs/fallen_symphony",
            lengthInSeconds = 567.4f,
            comparatorOutput = 9,
        ),
        MusicDiscDefinition(
            id = "firmaozo",
            title = "firmaozo",
            soundPath = "discs/firmaozo",
            lengthInSeconds = 113.0f,
            comparatorOutput = 10,
        ),
        MusicDiscDefinition(
            id = "gengaozo",
            title = "-45 - G e n g a o z o",
            soundPath = "discs/gengaozo",
            lengthInSeconds = 180.5f,
            comparatorOutput = 11,
        ),
        MusicDiscDefinition(
            id = "gargoyle",
            title = "Sanxion7 - Gargoyle",
            soundPath = "discs/gargoyle",
            lengthInSeconds = 387.4f,
            comparatorOutput = 12,
        ),
        MusicDiscDefinition(
            id = "genoicider",
            title = "DJ Myosuke - GENOCIDER",
            soundPath = "discs/genoicider",
            lengthInSeconds = 137.3f,
            comparatorOutput = 13,
        ),
        MusicDiscDefinition(
            id = "eden",
            title = "Gram - eden",
            soundPath = "discs/eden",
            lengthInSeconds = 144.6f,
            comparatorOutput = 14,
        ),
        MusicDiscDefinition(
            id = "smutna_pani",
            title = "Team Grimoire vs. Laur - Grievous Lady",
            soundPath = "discs/smutna_pani",
            lengthInSeconds = 141.2f,
            comparatorOutput = 15,
        ),
        MusicDiscDefinition(
            id = "hava_nagila",
            title = "Hava Nagila",
            soundPath = "discs/hava_nagila",
            lengthInSeconds = 137.3f,
            comparatorOutput = 1,
        ),
        MusicDiscDefinition(
            id = "hitsugi",
            title = "Plastic feat. Sakito - Hitsugi to Futago [1.25]",
            soundPath = "discs/hitsugi",
            lengthInSeconds = 115.9f,
            comparatorOutput = 2,
        ),
        MusicDiscDefinition(
            id = "mendes",
            title = "Humanoid - Mendes",
            soundPath = "discs/mendes",
            lengthInSeconds = 116.9f,
            comparatorOutput = 3,
        ),
        MusicDiscDefinition(
            id = "gwalt",
            title = "Imil & m1dlet - Bailandorape",
            soundPath = "discs/gwalt",
            lengthInSeconds = 182.3f,
            comparatorOutput = 4,
        ),
        MusicDiscDefinition(
            id = "makiba",
            title = "Jea - Makiba",
            soundPath = "discs/makiba",
            lengthInSeconds = 125.9f,
            comparatorOutput = 5,
        ),
        MusicDiscDefinition(
            id = "strong_280",
            title = "katagiri - STRONG 280",
            soundPath = "discs/strong_280",
            lengthInSeconds = 258.6f,
            comparatorOutput = 6,
        ),
        MusicDiscDefinition(
            id = "tool_assisted",
            title = "Kobairo - Tool Assisted Speedcore",
            soundPath = "discs/tool_assisted",
            lengthInSeconds = 254.6f,
            comparatorOutput = 7,
        ),
        MusicDiscDefinition(
            id = "bookmaker",
            title = "Kobaryo - Bookmaker",
            soundPath = "discs/bookmaker",
            lengthInSeconds = 263.3f,
            comparatorOutput = 8,
        ),
        MusicDiscDefinition(
            id = "last_wish",
            title = "Kry.exe feat. Ice - Last Wish",
            soundPath = "discs/last_wish",
            lengthInSeconds = 333.0f,
            comparatorOutput = 9,
        ),
        MusicDiscDefinition(
            id = "exitium",
            title = "Laur - Exitium",
            soundPath = "discs/exitium",
            lengthInSeconds = 140.3f,
            comparatorOutput = 10,
        ),
        MusicDiscDefinition(
            id = "dangerous_jungle",
            title = "Laur - DANGEROOOOUS JUNGLE (Extended)",
            soundPath = "discs/dangerous_jungle",
            lengthInSeconds = 240.0f,
            comparatorOutput = 11,
        ),
        MusicDiscDefinition(
            id = "doppelganger",
            title = "LeaF - Doppelganger",
            soundPath = "discs/doppelganger",
            lengthInSeconds = 266.5f,
            comparatorOutput = 12,
        ),
        MusicDiscDefinition(
            id = "lost_requiem",
            title = "Ludicin - Lost Requiem",
            soundPath = "discs/lost_requiem",
            lengthInSeconds = 559.7f,
            comparatorOutput = 13,
        ),
        MusicDiscDefinition(
            id = "regulus",
            title = "Ludicin - Onus Regulus",
            soundPath = "discs/regulus",
            lengthInSeconds = 207.5f,
            comparatorOutput = 14,
        ),
        MusicDiscDefinition(
            id = "bol",
            title = "LV.4 - B.O.L.",
            soundPath = "discs/bol",
            lengthInSeconds = 223.7f,
            comparatorOutput = 15,
        ),
        MusicDiscDefinition(
            id = "resonant",
            title = "Nekomata Master & Camellia - Resonant",
            soundPath = "discs/resonant",
            lengthInSeconds = 125.5f,
            comparatorOutput = 1,
        ),
        MusicDiscDefinition(
            id = "silentroom",
            title = "Nhelv - Silentroom",
            soundPath = "discs/silentroom",
            lengthInSeconds = 162.6f,
            comparatorOutput = 2,
        ),
        MusicDiscDefinition(
            id = "podsumowanie",
            title = "SitekX & Tidek - Podsumowanie pierwszego dnia rozgrywek grupowych MP4K",
            soundPath = "discs/podsumowanie",
            lengthInSeconds = 201.0f,
            comparatorOutput = 3,
        ),
        MusicDiscDefinition(
            id = "777",
            title = "RoughSketch - 777",
            soundPath = "discs/777",
            lengthInSeconds = 130.0f,
            comparatorOutput = 4,
        ),
        MusicDiscDefinition(
            id = "666",
            title = "RoughSketch - 666",
            soundPath = "discs/666",
            lengthInSeconds = 120.4f,
            comparatorOutput = 5,
        ),
        MusicDiscDefinition(
            id = "far_in_the_blue_sky",
            title = "Saikoro - Far in the blue sky",
            soundPath = "discs/far_in_the_blue_sky",
            lengthInSeconds = 187.1f,
            comparatorOutput = 6,
        ),
        MusicDiscDefinition(
            id = "ultimate_force",
            title = "Sakuzyo - Ultimate Force",
            soundPath = "discs/ultimate_force",
            lengthInSeconds = 149.3f,
            comparatorOutput = 7,
        ),
        MusicDiscDefinition(
            id = "sambaland",
            title = "SAMBA MASTER -SATOH- - Dark Sambaland",
            soundPath = "discs/sambaland",
            lengthInSeconds = 150.0f,
            comparatorOutput = 8,
        ),
        MusicDiscDefinition(
            id = "cyberia",
            title = "Sewerslvt - Cyberia lyr. 3",
            soundPath = "discs/cyberia",
            lengthInSeconds = 218.4f,
            comparatorOutput = 9,
        ),
        MusicDiscDefinition(
            id = "rose_quartz",
            title = "SHIKI - Rose Quartz",
            soundPath = "discs/rose_quartz",
            lengthInSeconds = 95.0f,
            comparatorOutput = 10,
        ),
        MusicDiscDefinition(
            id = "aegleseeker",
            title = "Silentroom vs Frums - Aegleseeker",
            soundPath = "discs/aegleseeker",
            lengthInSeconds = 150.0f,
            comparatorOutput = 11,
        ),
        MusicDiscDefinition(
            id = "trauma",
            title = "Hosoe Shinji - SON OF SUN",
            soundPath = "discs/trauma",
            lengthInSeconds = 103.2f,
            comparatorOutput = 12,
        ),
        MusicDiscDefinition(
            id = "supersonic_wayfarer",
            title = "Ribons - SUPERSONIC⟩⟩WAYFARER",
            soundPath = "discs/supersonic_wayfarer",
            lengthInSeconds = 465.0f,
            comparatorOutput = 13,
        ),
        MusicDiscDefinition(
            id = "swampgator",
            title = "Zekk - Swampgator (?)",
            soundPath = "discs/swampgator",
            lengthInSeconds = 246.7f,
            comparatorOutput = 14,
        ),
        MusicDiscDefinition(
            id = "arcana_eden",
            title = "Team Grimoire vs. Sakuzyo vs. Laur - Arcana Eden",
            soundPath = "discs/arcana_eden",
            lengthInSeconds = 185.0f,
            comparatorOutput = 15,
        ),
        MusicDiscDefinition(
            id = "teto",
            title = "teto teto teto teto teto teto teto teto teto teto teto teto teto teto",
            soundPath = "discs/teto",
            lengthInSeconds = 26.4f,
            comparatorOutput = 1,
        ),
        MusicDiscDefinition(
            id = "forgoren",
            title = "The Ghost Of 3.13 - Forgoren [1.4 + pitch]",
            soundPath = "discs/forgoren",
            lengthInSeconds = 172.2f,
            comparatorOutput = 2,
        ),
        MusicDiscDefinition(
            id = "regret",
            title = "TypeMars - Triumph & Regret",
            soundPath = "discs/regret",
            lengthInSeconds = 324.0f,
            comparatorOutput = 3,
        ),
        MusicDiscDefinition(
            id = "whos_that_boy",
            title = "Dr Bombay Official - Who's That Boy (?)",
            soundPath = "discs/whos_that_boy",
            lengthInSeconds = 197.9f,
            comparatorOutput = 4,
        ),
        MusicDiscDefinition(
            id = "multivversum",
            title = "Wydział Inżynierii Dźwięku MP4K - Across the MůLtiVVersum",
            soundPath = "discs/multivversum",
            lengthInSeconds = 667.7f,
            comparatorOutput = 5,
        ),
        MusicDiscDefinition(
            id = "stresstest",
            title = "yax03 - stresstest",
            soundPath = "discs/stresstest",
            lengthInSeconds = 300.6f,
            comparatorOutput = 6,
        ),
        MusicDiscDefinition(
            id = "decoy",
            title = "Yooh - Decoy",
            soundPath = "discs/decoy",
            lengthInSeconds = 258.7f,
            comparatorOutput = 7,
        ),
        MusicDiscDefinition(
            id = "decadance",
            title = "Yooh - Deca Dance",
            soundPath = "discs/decadance",
            lengthInSeconds = 124.3f,
            comparatorOutput = 8,
        ),
        MusicDiscDefinition(
            id = "testify",
            title = "void (Mournfinale) feat. Hoshikuma Minami - Testify",
            soundPath = "discs/testify",
            lengthInSeconds = 214.3f,
            comparatorOutput = 9,
        ),
        MusicDiscDefinition(
            id = "icicle_stinger",
            title = "ROKINA - Icicle Stinger",
            soundPath = "discs/icicle_stinger",
            lengthInSeconds = 138.0f,
            comparatorOutput = 10,
        ),
        MusicDiscDefinition(
            id = "new_york_back_raise",
            title = "saaa + kei_iwata + stuv + *wakadori - New York Back Raise",
            soundPath = "discs/new_york_back_raise",
            lengthInSeconds = 157.6f,
            comparatorOutput = 11,
        ),
        MusicDiscDefinition(
            id = "potential",
            title = "TAG - POTENTIAL",
            soundPath = "discs/potential",
            lengthInSeconds = 139.5f,
            comparatorOutput = 12,
        ),
        MusicDiscDefinition(
            id = "zloty_krol",
            title = "Daisuke Anayama - Konton wo koeshi warera ga shinsei naru tyuritunushi wo tataeyo",
            soundPath = "discs/zloty_krol",
            lengthInSeconds = 152.3f,
            comparatorOutput = 13,
        ),
        MusicDiscDefinition(
            id = "rainshower",
            title = "Silentroom - Rainshower",
            soundPath = "discs/rainshower",
            lengthInSeconds = 226.5f,
            comparatorOutput = 14,
        ),
        MusicDiscDefinition(
            id = "particle_colliter",
            title = "Kou! - High Speed Particle Collider-beam Accelerator",
            soundPath = "discs/particle_colliter",
            lengthInSeconds = 446.1f,
            comparatorOutput = 15,
        ),
    )
}

